---
- hosts: zkhosts
  become: true
  connection: ssh
  vars:
    - brokerid: "{{ inventory_hostname | regex_search('(gordon-zk-[1-9]\\.foo\\.bar)') | regex_replace('\\.foo\\.bar', '') | regex_replace('^gordon-zk-', '') }}"
    - zookeeperinfo: gordon-zk-1.foo.bar:2181,gordon-zk-2.foo.bar:2181,gordon-zk-3.foo.bar:2181/kafka2
    - dir_path: /data/kafka2-logs
  roles:
    - common
    - kafka