---
- hosts: kafkahosts
  become: true
  connection: ssh
  vars:
    - zookeeperinfo: gordon-zk-1.foo.bar:2181,gordon-zk-2.foo.bar:2181,gordon-zk-3.foo.bar:2181/kafka1
    - dir_path: /data/kafka1-logs
  roles:
    - common
    - kafka