# prometheus config
global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'gordon-jmx-kafka'
    static_configs:
      - targets:
        - gordon-kafka-1.foo.bar:7071
        - gordon-kafka-2.foo.bar:7071
        - gordon-kafka-3.foo.bar:7071

  - job_name: 'gordon-kafka-nodes'
    static_configs:
      - targets:
          - gordon-kafka-1.foo.bar:9100
          - gordon-kafka-2.foo.bar:9100
          - gordon-kafka-3.foo.bar:9100

  - job_name: 'gordon-kafka-exporter'
    static_configs:
      - targets:
          - gordon-kafka-1.foo.bar:9308
          - gordon-kafka-2.foo.bar:9308
          - gordon-kafka-3.foo.bar:9308