brokerid: "{{ inventory_hostname | regex_search('(gordon-kafka-[1-9]\\.foo\\.bar)') | regex_replace('\\.foo\\.bar', '') | regex_replace('^gordon-kafka-', '') }}"
zookeeperinfo: gordon-zk-1.foo.bar:2181,gordon-zk-2.foo.bar:2181,gordon-zk-3.foo.bar:2181
dir_path: /data/kafka-logs